Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -14,34 +14,46 @@ jobs:
         uses: docker/setup-buildx-action@v2
 
       - name: Build Docker Image
-        working-directory: simple-node-app
-        run: |
-          echo "Building Docker image..."
-          docker build -t node-app .
-          if [ $? -ne 0 ]; then
-            echo "Docker build failed"
-            exit 1
-          fi
+        working-directory: saveforlater-backend
+        run: docker build -t my-app:latest .
 
       - name: Stop Existing Containers
-        working-directory: simple-node-app
-        run: |
-          echo "Stopping existing containers..."
-          docker compose down
-          if [ $? -ne 0 ]; then
-            echo "Failed to stop existing containers"
-            exit 1
-          fi
+        working-directory: saveforlater-backend
+        run: docker compose down
 
       - name: Start Containers
-        working-directory: simple-node-app
-        run: |
-          echo "Starting containers..."
-          docker compose up -d
-          if [ $? -ne 0 ]; then
-            echo "Failed to start containers"
-            exit 1
-          fi
+        working-directory: saveforlater-backend
+        run: docker compose up -d
+
+      # - name: Build Docker Image
+      #   working-directory: simple-node-app
+      #   run: |
+      #     echo "Building Docker image..."
+      #     docker build -t node-app .
+      #     if [ $? -ne 0 ]; then
+      #       echo "Docker build failed"
+      #       exit 1
+      #     fi
+
+      # - name: Stop Existing Containers
+      #   working-directory: simple-node-app
+      #   run: |
+      #     echo "Stopping existing containers..."
+      #     docker compose down
+      #     if [ $? -ne 0 ]; then
+      #       echo "Failed to stop existing containers"
+      #       exit 1
+      #     fi
+
+      # - name: Start Containers
+      #   working-directory: simple-node-app
+      #   run: |
+      #     echo "Starting containers..."
+      #     docker compose up -d
+      #     if [ $? -ne 0 ]; then
+      #       echo "Failed to start containers"
+      #       exit 1
+      #     fi
 
       - name: Wait for containers to start
         run: |
